# A name for your workflow
name: My Custom Email Action

# This defines the trigger for the action
on:
  # Run this workflow on any push to the main branch
  push:
    branches: [ main ]

# A workflow is made up of one or more jobs
jobs:
  build:
    # The type of virtual machine to run the job on
    runs-on: ubuntu-latest

    # The sequence of tasks to be executed
    steps:
      # This is the custom step with your email in the name
      - name: A step run by 23f3003694@ds.study.iitm.ac.in
        run: echo "Hello from my custom step!"
